### PR TITLE
Create index.js so standard node requires work

### PR DESCRIPTION
**Pull request by halkeye**
I'm working on a mono repo with gatsby 3 and yarn 2, and this module won't import. A simple index.js fixes the issue.

### CODE REVIEW

**Comment by guilhermebellotti** [comment]
Hey @halkeye
How are you? Thanks for contribution and help for maintain this repo updated.

I took advantage of your update and updated some dependencies too

**Comment by halkeye** [comment]
oh awesome. I fully expected this never to be merged so its so exciting to see it get merged

**Comment by halkeye** [comment]
oh it needs to be excluded from .gitignore

**Comment by halkeye** [comment]
i guess not since its merged, but should be excluded

**Comment by guilhermebellotti** [comment]
Truth! I did the removal in .gitignore

**Pull request merged**
