### PR TITLE
Update to Gatsby 3.1.x

### PR DESCRIPTION
**Pull request by guilhermebellotti**
## Warnings Gatsby 3
As mentioned by our friend @sklawren in https://github.com/pocorschi/gatsby-plugin-google-fonts-v2/issues/7, the plugin was generating **warnings on the console**.

## Updates for support Gatsby 3
To resolve this, I **updated the dependencies**. In addition, I took advantage and tried to facilitate the reading of the readme (sorry, I tried haha). Below are the prints

> #Warnings in console
> warnings in console

The updates did not affect the project structures or cause any breakchange. Note the tests

> $ yarn test
> yarn test

> $ yarn coverage
> yarn coverage

## Results after updates
After updates in plugin, the result:

> after updates

### CODE REVIEW

**Comment by brandonwkipp** [comment]
@pocorschi Any chance this will get merged soon?

**Comment by wasurocks** [comment]
+1 Please merge this

**Comment by wasurocks** [comment]
@guilhermebellotti I've decided to install your fork of the repo for now. Really appreciate it!

**Comment by guilhermebellotti** [comment]
> @guilhermebellotti I've decided to install your fork of the repo for now. Really appreciate it!

Thk! I'm also using my fork for now

**Comment by pocorschi** [comment]
@guilhermebellotti  - merged and released to npm. Sorry about the delay. Not really using Gatsby, so if you'd like to help maintain it that would be  🚀

**Comment by guilhermebellotti** [comment]
> @guilhermebellotti - merged and released to npm. Sorry about the delay. Not really using Gatsby, so if you'd like to help maintain it that would be 🚀

thank you very much @pocorschi !
Whatever I can help, i'm in

**Pull request merged**
